Gateway: don't crash if latest repo version number is unspecified

diff --git a/kubernetes/gateway-deployment.yml b/kubernetes/gateway-deployment.yml
--- a/kubernetes/gateway-deployment.yml
+++ b/kubernetes/gateway-deployment.yml
@@ -16,22 +16,42 @@ spec:
     spec:
       initContainers:
         - name: init
-          image: nginx:1.19-alpine
+          image: ellerbrock/alpine-bash-curl-ssl:0.3.0
           command:
-            - /bin/sh
+            - /bin/bash
             - '-c'
             - |
               set -e
 
-              APT_LATEST_VERSION=$(curl -fsSL https://storage.googleapis.com/fullstaq-ruby-server-edition-apt-repo/versions/latest_version.txt)
-              YUM_LATEST_VERSION=$(curl -fsSL https://storage.googleapis.com/fullstaq-ruby-server-edition-yum-repo/versions/latest_version.txt)
+              function fetch_repo_version()
+              {
+                local TYPE="$1"
+                local TYPE_LC="$2"
+                local URL="https://storage.googleapis.com/fullstaq-ruby-server-edition-${TYPE_LC}-repo/versions/latest_version.txt"
+                local VERSION
 
-              echo "+ APT latest version: $APT_LATEST_VERSION"
-              echo "+ YUM latest version: $YUM_LATEST_VERSION"
+                echo " --> Checking $TYPE repo latest version" >&2
+                echo "     $URL" >&2
+                CODE=$(curl -sSL -w '%{http_code}' -o output.txt "$URL")
+                if [[ "$CODE" =~ ^2 ]]; then
+                  VERSION=$(cat output.txt)
+                  echo "     Result: $VERSION" >&2
+                  echo "$VERSION"
+                elif [[ "$CODE" = 404 ]]; then
+                  echo "     Result: unspecified (defaulting to 1)" >&2
+                  echo 1
+                else
+                  echo " --> Error fetching $URL: server returned HTTP code $CODE" >&2
+                  return 1
+                fi
+              }
+
+              APT_LATEST_VERSION=$(fetch_repo_version APT apt)
+              YUM_LATEST_VERSION=$(fetch_repo_version YUM yum)
 
               for F in /mnt/config/*; do
                 NAME=$(basename "$F")
-                echo "+ Processing $NAME"
+                echo " --> Processing $NAME"
                 sed "s|{APT_LATEST_VERSION}|$APT_LATEST_VERSION|g; s|{YUM_LATEST_VERSION}|$YUM_LATEST_VERSION|g" \
                   "$F" > "/mnt/processed-config/$NAME"
               done
